---
title: "manuscript"
author: "Andres Beltran - Yohanna Cabrera - Andres Cabrera"
date: "December 7, 2021"
output: 
  bookdown::word_document2:
      reference_docx: ESPPlantilla.docx
bibliography: references.bib
---

# Abstract
# Introduction
# Methods

## Statistical analysis


# Results and discussion 
```{r creating names list, echo = F,results='hide'}
names <- list.files(pattern = '.CSV')
```

```{r reading each data frame, echo = F}
spectra.list <- lapply(names, 
                       read.csv, 
                       header = F)
```

```{r extracting wave numbers, echo = F}
wavenumbers <- unlist(spectra.list[[1]][1])
```

```{r extracting just absorbances, echo = F}
spectra.list2 <- lapply(spectra.list, '[', 2)
```

```{r converting list of df to one df, echo = F}
spectra.df <- as.data.frame(
  t(as.data.frame(spectra.list2))
  )
```

```{r assigning names 1, echo = F}
rownames(spectra.df) <- names
colnames(spectra.df) <- wavenumbers
# gsub('.{6}$', '', names)
```

```{r checking names, echo = F, message = F,results='hide'}
head(names[1:3])
```

```{r correcting names length, echo = F, message = F,results='hide'}
names2 <- gsub('.{4}$', 
               '', 
               rownames(spectra.df))
head(names2[1:4])
```
```{r checking names 2, echo = F, message = F,results='hide'}
head(names2[292:318])
```
```{r correcting names length 2, echo = F, message = F,results='hide'}
names2[292:318] <- gsub('.{41}$', 
                        '',
                        rownames(
                          spectra.df
                          )[292:318])
head(names2[292:318])[1:4]
```

```{r assigning corrected names, echo = F,results='hide'}
rownames(spectra.df) <- names2
```

```{r creating factor for coloring replicas, attr.source="style='display:inline-block;'", collapse=TRUE, echo = F, message = F,results='hide'}
options(width = 30)
cols <- factor(gsub('.{2}$', '', names2))
head(cols)
```

```{r raw data plot, fig.cap="raw spectra of triplicated samples", echo = F, message = F}

for(i in  1:length(rownames(spectra.df))){
  
  plot(wavenumbers,
    spectra.df[i,],
    axes = F,
    xlab = '', 
    ylab = '',
    xlim = c(4000, 400),
    ylim= c(0,0.2),
    type = 'l',
    col =cols[i]

  )
  par(new = T)
}

box()
axis(1)
axis(2)
title(main = '',
      xlab = expression(
        paste('Wave number (cm'^'-1',
              ')')
        ),
      ylab ='absorbance (a.u.)')
```

```{r ROI selection, echo = F, message = F}
range1 <- spectra.df[,c(1:676)]
wavenumbers1 <- wavenumbers[c(1:676)]
```

```{r ROI plot, fig.cap="ROI spectra of triplicated samples", echo = F, message = F}
for(i in  1:length(rownames(range1))){

  plot(wavenumbers1,
    range1[i,],
    axes = F,
    xlab = '',
    ylab = '',
    xlim = c(1700, 400),
    ylim= c(0,0.2),
    type = 'l',
    col =cols[i]

  )
  par(new = T)
}

box()
axis(1)
axis(2)
title(main = '',
      xlab = expression(
        paste('Wave number (cm'^'-1',
              ')'
              )),
      ylab ='absorbance (a.u.)')

```

# Conclussion

# References

<div id = 'refs'> </div>